name: 'Data Caterer data flow testing'
description: 'Run integration tests for your application or job'
author: 'Data Catering'

# Define your inputs here.
inputs:
  configuration_file:
    description: 'File path to Data Caterer configuration file'
    default: 'data-caterer.yaml'
  insta_infra_folder:
    description: 'Folder to insta-infra'
    default: 'data-caterer-integration-test/insta-infra'
  base_folder:
    description: 'Folder to use for execution files'
    default: '/tmp/data-caterer'

# Define your outputs here.
outputs:
  results:
    description: 'Result of integration tests'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Checkout insta-infra repo
      uses: actions/checkout@v4
      with:
        repository: data-catering/insta-infra
        path: data-caterer-integration-test/insta-infra
    - name: Run integration tests
      uses: actions/github-script@v6
      with:
        script: |
          const { script } = require("${{github.action_path}}/dist/index.js")
          script()
      env:
        CONFIGURATION_FILE: ${{ inputs.configuration_file }}
        INSTA_INFRA_FOLDER: ${{ inputs.insta_infra_folder }}
        BASE_FOLDER: ${{ github.action_path }}
