name: 'Data Caterer data flow testing'
description: 'Run integration tests for your application or job'
author: 'Data Catering'

# Define your inputs here.
inputs:
  configuration-file:
    description: 'File path to Data Caterer configuration file'
    default: 'data-caterer.yaml'
  insta-infra-folder:
    description: 'Folder to insta-infra'
    default: 'data-caterer-integration-test/insta-infra'

# Define your outputs here.
outputs:
  results:
    description: 'Result of integration tests'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Checkout insta-infra repo
      uses: actions/checkout@v4
      with:
        repository: data-catering/insta-infra
        path: data-caterer-integration-test/insta-infra
    - name: Run integration tests
      uses: actions/github-script@v7
      with:
        configuration-file: ${{ inputs.configuration-file }}
        insta-infra-folder: ${{ inputs.insta-infra-folder }}
        script: |
          const script = require("${{github.action_path}}/dist/index.js")
          script({core})
